[package]
name = "bluepaper_core"
version = "0.0.1"
authors = ["Robert Bamler <robert.bamler@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark = { path = "../pulldown-cmark" }
log = "0.4"
