[package]
name = "bluepaper-wasm"
# description = "TODO"
authors = ["Robert Bamler <robert.bamler@gmail.com>"]
categories = ["wasm"]
edition = "2018"
readme = "README.md"
version = "0.0.1"

[lib]
crate-type = ["cdylib"]

[profile.release]
# This makes the compiled code faster and smaller, but it makes compiling slower,
# so it's only enabled in release mode.
lto = true

# Tell `rustc` to optimize for small code size.
opt-level = "s"

[features]
# If you uncomment this line, it will enable `wee_alloc`:
default = ["wee_alloc"]

[dependencies]
bluepaper_core = {path = "../core"}
js-sys = "0.3.22"
lazy_static = "1.4.0"
zip = {version = "0.5.3", default-features = false}

# The `wasm-bindgen` crate provides the bare minimum functionality needed
# to interact with JavaScript.
wasm-bindgen = "0.2.45"

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. However, it is slower than the default
# allocator, so it's not enabled by default.
wee_alloc = {version = "0.4.2", optional = true}

# The `web-sys` crate allows you to interact with the various browser APIs,
# like the DOM.
[dependencies.web-sys]
features = ["console"]
version = "0.3.22"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so it's only enabled
# in debug mode.
[target."cfg(debug_assertions)".dependencies]
console_error_panic_hook = "0.1.5"

# These crates are used for running unit tests.
[dev-dependencies]
futures = "0.3.19"
wasm-bindgen-futures = "0.4.29"
wasm-bindgen-test = "0.3.29"
