name: Test and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test-and-deploy:
    name: Test, build, and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install latest stable Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install node.js
        uses: actions/setup-node@v2

      - name: Get tools versions
        id: versions
        run: |
          echo "::set-output name=rustc::`rustc --version | awk '{print $2}'`"
          echo "::set-output name=node::`node --version`"

      - name: Cache backend (cargo) dependencies
        uses: actions/cache@v2
        with:
          path: |
            target
            .cargo_home
          key: ${{ runner.os }}-rustc-${{ steps.versions.outputs.rustc }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rustc-${{ steps.versions.outputs.rustc }}-
            ${{ runner.os }}-rustc-

      - name: Install tectonic dependencies
        run: sudo apt install -y libgraphite2-dev libicu-dev libpng-dev libfreetype-dev libfontconfig-dev

      - name: Run backend tests
        run: CARGO_HOME=.cargo_home cargo test

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0

      - name: Audit npm dependencies (with --audit-level=high)
        run: cd wasm && npm audit --audit-level=high

      - name: Cache frontend (npm) dependencies
        uses: actions/cache@v2
        with:
          path: wasm/node_modules
          key: ${{ runner.os }}-node-${{ steps.versions.outputs.node }}-${{ hashFiles('wasm/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ steps.versions.outputs.node }}-
            ${{ runner.os }}-node-

      - name: Install frontend (npm) dependencies
        run: cd wasm && npm install

      - name: Build app in release mode
        run: cd wasm && CARGO_HOME=../.cargo_home npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./wasm/dist
          commit_message: Deploy
